// 테스트 후 삭제 예정

export const mockData = [
  {
    _id: '5fb383b488749f1cb514c4cc',
    users: [{_id: '111', username: 'ss', gameIndex: 0}],
    isPlaying: true,
    gameInfo: {
      owner: '5fad203c450f12a788ed2f89',
      name: '광진구에서 하는 게임',
      address: '서울시 광진구',
      addressDetail: '신향빌라',
      location: [ 11, 12 ],
      timeLimit: 600000,
      quizList: [{
        _id: 1,
        index: 0,
        keyword: '바나나',
        quiz: '바나나를 먹은 사람은?',
        answer: '나',
        hint: '내 옆에 있던 사람',
      }, {
        _id: 2,
        index: 1,
        keyword: '커피',
        quiz: '커피를 먹은 사람은?',
        answer: '너',
        hint: '너 옆에 있던 사람',
      }, {
        _id: 3,
        index: 2,
        keyword: '컴퓨터',
        quiz: '컴퓨터로 유튜브 보는 사람?',
        answer: '몰라',
        hint: '나도 몰라',
      }],
    },
  },
  {
    _id: '5fb383d388749f1cb514c4d0',
    users: [{_id: '111', username: 'ss', gameIndex: 0}],
    isPlaying: true,
    gameInfo: {
      owner: '5face74b4cf3f8968894e73a',
      name: '바코에서 게임 할 사람 구함',
      address: '서울 강남구 대치동',
      addressDetail: '바닐라코딩 4층',
      location: [ 11, 12 ],
      timeLimit: 600000,
      quizList: [{
        _id: 1,
        index: 0,
        keyword: '바나나',
        quiz: '바나나를 먹은 사람은?',
        answer: '나',
        hint: '내 옆에 있던 사람',
      }, {
        _id: 2,
        index: 1,
        keyword: '커피',
        quiz: '커피를 먹은 사람은?',
        answer: '너',
        hint: '너 옆에 있던 사람',
      }, {
        _id: 3,
        index: 2,
        keyword: '컴퓨터',
        quiz: '컴퓨터로 유튜브 보는 사람?',
        answer: '몰라',
        hint: '나도 몰라',
      }],
    },
  },
  {
    _id: '5fb3843a2663d8a671de5af4',
    users: [{_id: '111', username: 'ss', gameIndex: 0}],
    isPlaying: false,
    gameInfo: {
      owner: '5face74b4cf3f8968894e73a',
      name: '왜 안들어오는 거야',
      address: '서울 강남구 대치동',
      addressDetail: '바닐라코딩 4층',
      location: [ 11, 12 ],
      timeLimit: 600000,
      quizList: [{
        _id: 1,
        index: 0,
        keyword: '바나나',
        quiz: '바나나를 먹은 사람은?',
        answer: '나',
        hint: '내 옆에 있던 사람',
      }, {
        _id: 2,
        index: 1,
        keyword: '커피',
        quiz: '커피를 먹은 사람은?',
        answer: '너',
        hint: '너 옆에 있던 사람',
      }, {
        _id: 3,
        index: 2,
        keyword: '컴퓨터',
        quiz: '컴퓨터로 유튜브 보는 사람?',
        answer: '몰라',
        hint: '나도 몰라',
      }],
    },
  },
  {
    _id: '5fb384462663d8a671de5af5',
    users: [{_id: '111', username: 'ss', gameIndex: 0}],
    isPlaying: false,
    gameInfo: {
      owner: '5fb0b90159fc360c7e6ea828',
      name: '들어왕',
      address: '서울 강남구 대치동',
      addressDetail: '바닐라코딩 4층',
      location: [ 11, 12 ],
      timeLimit: 600000,
      quizList: [{
        _id: 1,
        index: 0,
        keyword: '바나나',
        quiz: '바나나를 먹은 사람은?',
        answer: '나',
        hint: '내 옆에 있던 사람',
      }, {
        _id: 2,
        index: 1,
        keyword: '커피',
        quiz: '커피를 먹은 사람은?',
        answer: '너',
        hint: '너 옆에 있던 사람',
      }, {
        _id: 3,
        index: 2,
        keyword: '컴퓨터',
        quiz: '컴퓨터로 유튜브 보는 사람?',
        answer: '몰라',
        hint: '나도 몰라',
      }],
    },
  }
];
